### ISSUE TITLE
Output stacked rankings 

### ISSUE THREAD

**Issue by juliancleung** [uwblueprint/cookie-monster#18]
As a user I want to create stacked rankings based on the overall ratings of all the applicants. This list should be ordered from highest rated application to lowest rated application. A nice to have feature would be tie breakers determined by how users rated individual questions (the suggested rating). There should also be a threshold set at 5 applications that move to the next stage. 

Keep in mind that each application will have the ability to be dragged-and-dropped over the threshold in a future story.

Acceptance criteria: 
- users can see color blocks beside applications based on overall rating of the application (or based on whether its passed or failed)
- users can see a list of applications ordered by their overall rating
- users can see the name of the application and the overall rating
- users can see a threshold line at 5 applications that clearly indicates that the top applicants are the ones that have moved onto the next stage
- user can move an application over or under the threshold line to change its status
- applications below the threshold are gray

Mock-up:
https://www.figma.com/file/195UMD7gVEpQKB39c0bSz7/SVP-High-Fidelity?node-id=41%3A10506

**Comment by billxsheng** [comment]
Talked to Joe and Nick about the first point in the acceptance criteria and decided that it was not needed.
