### ISSUE TITLE
List of applications

### ISSUE THREAD

**Issue by juliancleung** [uwblueprint/cookie-monster#7]
As a user, I want to see the full list of applications in a table and be able to go into individual applications from the list.

Acceptance criteria:
- user can identify the stage the application is in (full application or letter of interest)*
- user can enter each individual application from the list of applications
- user can see when they last reviewed the application
- user can see the overall rating of the application
- applications are sorted alphabetically

*The status column should not appear for applications currently in review. The status column should appear for application stages that have passed. For the SVP use case, the status column should appear when the current stage is "Full Application" and the user is looking at the "Letter of Interest" applications but should not appear in the "Full Application" list.

Mock-up:
https://www.figma.com/file/195UMD7gVEpQKB39c0bSz7/SVP-High-Fidelity?node-id=6%3A2

**Comment by nkxy** [comment]
https://www.figma.com/file/195UMD7gVEpQKB39c0bSz7/SVP-High-Fidelity?node-id=79%3A3431 Figma Screen
