### ISSUE TITLE
Allow user to rate an application or answer

### ISSUE THREAD

**Issue by juliancleung** [uwblueprint/cookie-monster#9]
As a user I want to be able to rate a full application or answer

Acceptance criteria:
- user can rate the full application on a 5 point scale

Mockup:
https://www.figma.com/file/195UMD7gVEpQKB39c0bSz7/SVP-High-Fidelity?node-id=11%3A1156

**Comment by nkxy** [comment]
Figma Component
https://www.figma.com/file/VMiEadHsaUzzsiATu5HV0D/SVP-Component-Library?node-id=110%3A111
